apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  namespace: nfs
spec:
  accessModes:
    - ReadWriteMany       # NFS obsługuje równoczesny zapis z wielu podów
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-sc  # musi zgadzać się z utworzoną StorageClass
