apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: nfs
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: nginx 
        image: nginx:alpine 
        ports:
        - containerPort: 80 
        volumeMounts:
        - name: web-content  # mount a volume web-content
          mountPath: /usr/share/nginx/html # mount it at nginx web root
      volumes:
      - name: web-content
        persistentVolumeClaim:
          claimName: web-pvc # bind the volume to the existing PVC web-pvc
