apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  namespace: nfs
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-sc  # must match the created StorageClass
