apiVersion: v1
kind: Service
metadata:
  name: web-server-svc
  namespace: nfs
spec:
  selector:
    app: web-server
  ports:
    - port: 80        # external port
      targetPort: 80  # port in pod
      protocol: TCP
  type: LoadBalancer 
