persistence:
  enabled: false #We disable the use of EBS

storageClass:
  create: true # Provisioner will create a new StorageClass automatically
  name: nfs-sc # The name of the StorageClass that will be used in the PVC later
  defaultClass: false # I do not set this StorageClass as default in the cluster
